---
- name: Install php-fpm and deps
  apt: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-mbstring
    - php-mysql
    - php-mcrypt
    - libphp-phpmailer
    - libphp-simplepie
    - php-xml
  
- name: Install php-extensions
  apt: name={{ item }} state=present
  with_items: "{{ php_extensions }}"
  when: php_extensions is defined

- name: Enable php-extensions
  shell: phpenmod {{ item }}
  with_items: php_extensions
  when: php_extensions is defined
  notify: restart php-fpm