---
ansible_host: "{{ vault_ansible_host }}"
ansible_connection: ssh 
ansible_user: "{{ vault_ansible_user }}"
ansible_ssh_port: "{{ vault_ansible_ssh_port }}"
change_ssh_port: true
ssh_port: "{{ vault_ssh_port }}"
backup_user: "{{ vault_backup_user}}"
backup_passwd: "{{ vault_backup_passwd }}"