---
ansible_host: "{{ vault_ansible_host }}"
ansible_connection: ssh 
ansible_user: "{{ vault_ansible_user }}" 
ansible_ssh_port: "{{ vault_ansible_ssh_port }}"

server_name: peopleactmagazine.fr
mysql_root_pwd: "{{ vault_mysql_root_pwd }}"
borg_passphrase: "{{ vault_borg_passphrase }}"

remote_user_name: "{{ vault_remote_user_name }}"
remote_user_passwd: "{{ vault_remote_user_passwd }}"

databases:
  - database_name: peopleactmagazine
    database_user: peopleactmagazine
    database_passwd: "{{ vault_database_peopleactmagazine_passwd }}"

nginx_vhosts:
  - listen: "443 ssl http2"
    state: "present"
    https_redirect: true
    isSSLActive: true
    letsencryptDomainChain: "-d peopleactmagazine.fr -d www.peopleactmagazine.fr"
    certificateURI: "peopleactmagazine.fr"
    server_name: "peopleactmagazine.fr www.peopleactmagazine.fr"
    root: "/var/www/peopleactmagazine.fr"
    index: "index.php index.html"
    access_log: "/var/log/nginx/peopleactmagazine.fr.access.log"
    error_log: "/var/log/nginx/peopleactmagazine.fr.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "peopleactmagazine.fr.conf"
    isWordpress: true
    locations: 
      - path: "~* /(?:uploads|files)/.*\\.php$ "
        deny: all
      - path: "/"
        try_files: "$uri $uri/ /index.php?$args"
        index: "index index.php index.html index.htm"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max
      - path: "~ \\.php$"
        try_files: "$uri =404"
        fastcgi_split_path_info: "^(.+\\.php)(/.+)$"
        fastcgi_index: "index.php"
        fastcgi_pass: "unix:/var/run/php/php7.0-fpm.sock"
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name"
        include: fastcgi_params