---
site1_databases: 
  - database_name: montoitvert
    database_user: montoitvert
    database_passwd: "{{ vault_database_montoitvert_passwd }}"

site1_nginx_vhosts:
  - listen: "443 ssl http2"
    state: "present"
    https_redirect: true
    isSSLActive: true
    letsencryptDomainChain: "-d toni0.com -d www.toni0.com"
    certificateURI: "toni0.com"
    server_name: "toni0.com www.toni0.com"
    root: "/var/www/toni0.com"
    index: "index.php index.html"
    access_log: "/var/log/nginx/toni0.com.access.log"
    error_log: "/var/log/nginx/toni0.com.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "toni0.com.conf"
    locations: 
      - path: "~* /(?:uploads|files)/.*\\.php$ "
        deny: all
      - path: "/"
        try_files: "$uri $uri/ /index.php?$args"
        index: "index index.php index.html index.htm"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max
      - path: "~ \\.php$"
        try_files: "$uri =404"
        fastcgi_split_path_info: "^(.+\\.php)(/.+)$"
        fastcgi_index: "index.php"
        fastcgi_pass: "unix:/var/run/php/php7.0-fpm.sock"
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name"
        include: fastcgi_params