---

sotraso_nginx_vhosts:
  - listen: "80" #"443 ssl http2"
    state: "present"
    https_redirect: false
    isSSLActive: false
    letsencryptDomainChain: "-d sotraso.fr -d www.sotraso.fr"
    certificateURI: "sotraso.fr"
    server_name: "sotraso.fr www.sotraso.fr"
    root: "/var/www/sotraso.fr"
    index: "index.html"
    access_log: "/var/log/nginx/sotraso.fr.access.log"
    error_log: "/var/log/nginx/sotraso.fr.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "sotraso.fr.conf"
    isWordpress: false
    locations: 
      - path: "/"
        try_files: "$uri $uri/ /index.html"
        index: "index.html index.php"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max