---

portdelavigne_nginx_vhosts:
  - listen: "443 ssl http2"
    state: "present"
    https_redirect: true
    isSSLActive: true
    letsencryptDomainChain: "-d portdelavigne.fr -d www.portdelavigne.fr"
    certificateURI: "portdelavigne.fr"
    server_name: "portdelavigne.fr www.portdelavigne.fr"
    root: "/var/www/portdelavigne.fr"
    index: "index.php index.html"
    access_log: "/var/log/nginx/portdelavigne.fr.access.log"
    error_log: "/var/log/nginx/portdelavigne.fr.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "portdelavigne.fr.conf"
    isWordpress: false
    locations: 
      - path: "/"
        rewrites:
          - condition: "!-e $request_filename"
            scheme: "^/([^/]+)/?$ /index.php?p=$1 last"
        try_files: "$uri $uri/ /index.php?$args"
        index: "index.html index.php"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max
      - path: "~ \\.php$"
        try_files: "$uri =404"
        fastcgi_split_path_info: "^(.+\\.php)(/.+)$"
        fastcgi_index: "index.php"
        fastcgi_pass: "unix:/var/run/php/php5.6-fpm.sock"
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name"
        include: fastcgi_params

portdelavigne_databases:
  - database_name: portdelavigne
    database_user: portdelavigne
    database_passwd: "{{ vault_database_portdelavigne_passwd }}"
