---

webop_nginx_vhosts:
  - listen: "443 ssl http2"
    state: "present"
    https_redirect: true
    isSSLActive: true
    letsencryptDomainChain: "-d webop.fr -d www.webop.fr"
    certificateURI: "webop.fr"
    server_name: "webop.fr www.webop.fr"
    root: "/var/www/webop.fr"
    index: "index.php index.html"
    access_log: "/var/log/nginx/webop.fr.access.log"
    error_log: "/var/log/nginx/webop.fr.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "webop.fr.conf"
    locations: 
      - path: "~* /(?:uploads|files)/.*\\.php$ "
        deny: all
      - path: "/"
        try_files: "$uri $uri/ /index.php?$args"
        index: "index index.php index.html index.htm"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max
      - path: "~ \\.php$"
        try_files: "$uri =404"
        fastcgi_split_path_info: "^(.+\\.php)(/.+)$"
        fastcgi_index: "index.php"
        fastcgi_pass: "unix:/var/run/php/php7.0-fpm.sock"
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name"
        include: fastcgi_params



webop_databases:
  - database_name: webop
    database_user: webop
    database_passwd: "{{ vault_database_webop_passwd }}"