---

enrobes_nginx_vhosts:
  - listen: "80" #"443 ssl http2"
    state: "present"
    https_redirect: false
    isSSLActive: false
    letsencryptDomainChain: "-d enrobes.eu -d www.enrobes.eu"
    certificateURI: "enrobes.eu"
    server_name: "enrobes.eu www.enrobes.eu"
    root: "/var/www/enrobes.eu"
    index: "index.php index.html"
    access_log: "/var/log/nginx/enrobes.eu.access.log"
    error_log: "/var/log/nginx/enrobes.eu.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "enrobes.eu.conf"
    isWordpress: false
    locations: 
      - path: "/"
        rewrites:
          - condition: "!-e $request_filename"
            scheme: "^/([^/]+)/?$ /index.php?p=$1 last"
        try_files: "$uri $uri/ /index.php?$args"
        index: "index.html index.php"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max
      - path: "~ \\.php$"
        try_files: "$uri =404"
        fastcgi_split_path_info: "^(.+\\.php)(/.+)$"
        fastcgi_index: "index.php"
        fastcgi_pass: "unix:/var/run/php/php5.6-fpm.sock"
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name"
        include: fastcgi_params

enrobes_databases:
  - database_name: enrobes
    database_user: enrobes
    database_passwd: "{{ vault_database_enrobes_passwd }}"