---
- name: Install sendmail
  apt:
    name: sendmail
    state: present
    update_cache: yes

- name: Install php.ini 
  template: src=php.ini dest=/etc/php/7.0/fpm/php.ini

- name: restart php-fpm
  service: name=php7.0-fpm state=restarted
