---
- name: Install Mysql package
  apt: name={{ item }} state=present
  with_items:
   - mariadb-server
   - python-mysqldb
   - python-selinux
   - python-semanage

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_pwd }}"
    login_user: root
    login_password: "{{ mysql_root_pwd }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost 

- name: Creating the databases
  mysql_db:
    name: "{{ item.database_name }}"
    state: present
    login_host: "localhost"
    login_user: root
    login_password: "{{ mysql_root_pwd }}"
    login_port: 3306
  with_items: "{{ databases }}"
  when: databases is defined

- name: Creating the users
  mysql_user:
    name: "{{ item.database_user }}"
    host: "localhost"
    password: "{{ item.database_passwd }}"
    login_host: "localhost"
    login_user: root
    login_password: "{{ mysql_root_pwd }}"
    login_port: 3306
    priv: "{{item.database_name}}.*:ALL,GRANT"
  with_items: "{{ databases }}"
  when: databases is defined

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
