---
ansible_host: "{{ vault_ansible_host }}"
ansible_connection: ssh 
ansible_user: "{{ vault_ansible_user }}" 
ansible_ssh_port: "{{ vault_ansible_ssh_port }}"

enable_sendmail: true
sendmail_envelope: contact@montoitvert.fr
server_name: montoitvert.fr
mysql_root_pwd: "{{ vault_mysql_root_pwd }}"
borg_passphrase: "{{ vault_borg_passphrase }}"

remote_user_name: "{{ vault_remote_user_name }}"
remote_user_passwd: "{{ vault_remote_user_passwd }}"

databases:
  - database_name: montoitvert
    database_user: montoitvert
    database_passwd: "{{ vault_database_montoitvert_passwd }}"
  - database_name: mygreenroof
    database_user: mygreenroof
    database_passwd: "{{ vault_database_mygreenroof_passwd }}"

nginx_vhosts:
  - listen: "443 ssl http2"
    state: "present"
    https_redirect: true
    isSSLActive: true
    letsencryptDomainChain: "-d montoitvert.fr -d www.montoitvert.fr"
    certificateURI: "montoitvert.fr"
    server_name: "montoitvert.fr www.montoitvert.fr"
    root: "/var/www/montoitvert.fr"
    index: "index.php index.html"
    access_log: "/var/log/nginx/montoitvert.fr.access.log"
    error_log: "/var/log/nginx/montoitvert.fr.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "montoitvert.fr.conf"
    locations: 
      - path: "~* /(?:uploads|files)/.*\\.php$ "
        deny: all
      - path: "/"
        try_files: "$uri $uri/ /index.php?$args"
        index: "index index.php index.html index.htm"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max
      - path: "~ \\.php$"
        try_files: "$uri =404"
        fastcgi_split_path_info: "^(.+\\.php)(/.+)$"
        fastcgi_index: "index.php"
        fastcgi_pass: "unix:/var/run/php/php7.0-fpm.sock"
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name"
        include: fastcgi_params
  - listen: "443 ssl http2"
    state: "present"
    https_redirect: true
    isSSLActive: true
    letsencryptDomainChain: "-d my-green-roof.com -d www.my-green-roof.com"
    certificateURI: "my-green-roof.com"
    server_name: "my-green-roof.com www.my-green-roof.com"
    root: "/var/www/my-green-roof.com"
    index: "index.php index.html"
    access_log: "/var/log/nginx/my-green-roof.com.access.log"
    error_log: "/var/log/nginx/my-green-roof.com.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "my-green-roof.com.conf"
    locations: 
      - path: "~* /(?:uploads|files)/.*\\.php$ "
        deny: all
      - path: "/"
        try_files: "$uri $uri/ /index.php?$args"
        index: "index index.php index.html index.htm"
      - path: "~* \\.(gif|jpg|jpeg|png|css|js)$"
        expires: max
      - path: "~ \\.php$"
        try_files: "$uri =404"
        fastcgi_split_path_info: "^(.+\\.php)(/.+)$"
        fastcgi_index: "index.php"
        fastcgi_pass: "unix:/var/run/php/php7.0-fpm.sock"
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name"
        include: fastcgi_params
      # - path: 
      #   try_files:
      #   fastcgi_split_path_info: 
      #   index:
      #   deny: 
      #   fastcgi_index: 
      #   fastcgi_pass: 
      #   fastcgi_param: 
      #   include: 
      #   expires: 