---
ansible_host: IP
ansible_connection: ssh 
ansible_user: root 
ansible_ssh_port: 22

server_name: server.tld
mysql_root_pwd: rootpwd
borg_passphrase: borgpwd

remote_user_name: webopaccess
remote_user_passwd: "$6$pwd"

databases:
  - database_name: dbn
    database_user: dbu
    database_passwd: dbp

nginx_vhosts:
  - listen: "443 ssl http2"
    state: "present"
    https_redirect: true
    isSSLActive: true
    letsencryptDomainChain: "-d server.tld -d www.server.tld"
    certificateURI: "server.tld"
    server_name: "server.tld www.server.tld"
    root: "/var/www/server.tld"
    index: "index.php index.html"
    access_log: "/var/log/nginx/server.tld.access.log"
    error_log: "/var/log/nginx/server.tld.error.log"
    template: "{{ nginx_vhost_template }}"
    filename: "server.tld.conf"
    locations: 
      # - path: 
      #   try_files:
      #   fastcgi_split_path_info: 
      #   index:
      #   deny: 
      #   fastcgi_index: 
      #   fastcgi_pass: 
      #   fastcgi_param: 
      #   include: 
      #   expires: 